{"filter":false,"title":"BB8CustomServiceMessage.srv","tooltip":"/unit_3_services/srv/BB8CustomServiceMessage.srv","ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":3,"column":41},"end":{"row":3,"column":41},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"hash":"5fdd71993578037178507d34f08aca14de40b36d","undoManager":{"mark":3,"position":3,"stack":[[{"start":{"row":0,"column":8},"end":{"row":0,"column":14},"action":"remove","lines":["radius"],"id":2},{"start":{"row":0,"column":8},"end":{"row":0,"column":9},"action":"insert","lines":["s"]}],[{"start":{"row":0,"column":9},"end":{"row":0,"column":10},"action":"insert","lines":["i"],"id":3}],[{"start":{"row":0,"column":10},"end":{"row":0,"column":11},"action":"insert","lines":["d"],"id":4}],[{"start":{"row":0,"column":11},"end":{"row":0,"column":12},"action":"insert","lines":["e"],"id":5}]]},"timestamp":1538117846000}