{"filter":false,"title":"MyCustomServiceMessage.srv","tooltip":"/my_custom_srv_msg_pkg/srv/MyCustomServiceMessage.srv","ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":3,"column":41},"end":{"row":3,"column":41},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"hash":"f820bf81bcfd22b87bf753a6c03a6a92135b3477","undoManager":{"mark":0,"position":0,"stack":[[{"start":{"row":0,"column":0},"end":{"row":3,"column":41},"action":"insert","lines":["float64 radius       # The distance of each side of the square","int32 repetitions    # The number of times BB-8 has to execute the square movement when the service is called","---","bool success         # Did it achieve it?"],"id":1}]]},"timestamp":1538115788000}